export const POSTS = [
    {
      _id: "1",
      text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
      img: "/posts/post1.png",
      user: {
        username: "rahul123",
        profileImg: "/avatars/boy1.png",
        fullName: "Rahul Sharma",
      },
      comments: [
        {
          _id: "1",
          text: "Nice Tutorial",
          user: {
            username: "priyapatel",
            profileImg: "/avatars/girl1.png",
            fullName: "Priya Patel",
          },
        },
      ],
      likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
    },
    {
      _id: "2",
      text: "How you guys doing? 😊",
      user: {
        username: "rahul123",
        profileImg: "/avatars/boy2.png",
        fullName: "Rahul Sharma",
      },
      comments: [
        {
          _id: "1",
          text: "Nice Tutorial",
          user: {
            username: "priyapatel",
            profileImg: "/avatars/girl2.png",
            fullName: "Priya Patel",
          },
        },
      ],
      likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
    },
    {
      _id: "3",
      text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
      img: "/posts/post2.png",
      user: {
        username: "amitkumar",
        profileImg: "/avatars/boy3.png",
        fullName: "Amit Kumar",
      },
      comments: [],
      likes: [
        "6658s891",
        "6658s892",
        "6658s893",
        "6658s894",
        "6658s895",
        "6658s896",
      ],
    },
    {
      _id: "4",
      text: "I'm learning GO this week. Any tips? 🤔",
      img: "/posts/post3.png",
      user: {
        username: "amitkumar",
        profileImg: "/avatars/boy3.png",
        fullName: "Amit Kumar",
      },
      comments: [
        {
          _id: "1",
          text: "Nice Tutorial",
          user: {
            username: "priyapatel",
            profileImg: "/avatars/girl3.png",
            fullName: "Priya Patel",
          },
        },
      ],
      likes: [
        "6658s891",
        "6658s892",
        "6658s893",
        "6658s894",
        "6658s895",
        "6658s896",
        "6658s897",
        "6658s898",
        "6658s899",
      ],
    },
  ];
  

export const USERS_FOR_RIGHT_PANEL = [
    {
      _id: "1",
      fullName: "Rahul Sharma",
      username: "rahul123",
      profileImg: "/avatars/boy2.png",
    },
    {
      _id: "2",
      fullName: "Priya Patel",
      username: "priyapatel",
      profileImg: "/avatars/girl1.png",
    },
    {
      _id: "3",
      fullName: "Amit Kumar",
      username: "amitkumar",
      profileImg: "/avatars/boy3.png",
    },
    {
      _id: "4",
      fullName: "Anjali Gupta",
      username: "anjali89",
      profileImg: "/avatars/girl2.png",
    },
  ];
  